// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PJATK_APBD_Cw7_s33611.Infrastructure;

#nullable disable

namespace PJATK_APBD_Cw7_s33611.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260509174605_Seed")]
    partial class Seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PJATK_APBD_Cw7_s33611.Models.Component", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("char(10)");

                    b.Property<int>("ComponentsManufacturersId")
                        .HasColumnType("int");

                    b.Property<int>("ComponentsTypesId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Code");

                    b.HasIndex("ComponentsManufacturersId");

                    b.HasIndex("ComponentsTypesId");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            Code = "MOBO123456",
                            ComponentsManufacturersId = 1,
                            ComponentsTypesId = 1,
                            Description = "Description of this mobo",
                            Name = "MOBO"
                        },
                        new
                        {
                            Code = "MOBO098765",
                            ComponentsManufacturersId = 2,
                            ComponentsTypesId = 1,
                            Description = "Description of other mobo",
                            Name = "MOBOX1"
                        },
                        new
                        {
                            Code = "RAM1234567",
                            ComponentsManufacturersId = 2,
                            ComponentsTypesId = 2,
                            Description = "Description of some RAM",
                            Name = "RAMX1"
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s33611.Models.ComponentManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FoundationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("ComponentManufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "ABR",
                            FoundationDate = new DateTime(2015, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "AbbreviationManufacturer"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "X1",
                            FoundationDate = new DateTime(2001, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "X1Industries"
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s33611.Models.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "MOBO",
                            Name = "Motherboard"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "RAM",
                            Name = "Random Access Memory"
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s33611.Models.PC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("float(5)");

                    b.HasKey("Id");

                    b.ToTable("PCs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "SomePC1",
                            Stock = 10,
                            Warranty = 3,
                            Weight = 15.5f
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "SomeOtherPC2",
                            Stock = 3,
                            Warranty = 1,
                            Weight = 20f
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s33611.Models.PCComponent", b =>
                {
                    b.Property<int>("PCId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentCode")
                        .HasColumnType("char(10)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("PCId", "ComponentCode");

                    b.HasIndex("ComponentCode");

                    b.ToTable("PCComponents");

                    b.HasData(
                        new
                        {
                            PCId = 1,
                            ComponentCode = "MOBO123456",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 1,
                            ComponentCode = "RAM1234567",
                            Amount = 2
                        },
                        new
                        {
                            PCId = 2,
                            ComponentCode = "MOBO098765",
                            Amount = 1
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s33611.Models.Component", b =>
                {
                    b.HasOne("PJATK_APBD_Cw7_s33611.Models.ComponentManufacturer", "ComponentManufacturer")
                        .WithMany()
                        .HasForeignKey("ComponentsManufacturersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PJATK_APBD_Cw7_s33611.Models.ComponentType", "ComponentType")
                        .WithMany()
                        .HasForeignKey("ComponentsTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentManufacturer");

                    b.Navigation("ComponentType");
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s33611.Models.PCComponent", b =>
                {
                    b.HasOne("PJATK_APBD_Cw7_s33611.Models.Component", "Component")
                        .WithMany("PCComponents")
                        .HasForeignKey("ComponentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PJATK_APBD_Cw7_s33611.Models.PC", "PC")
                        .WithMany("PCComponents")
                        .HasForeignKey("PCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("PC");
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s33611.Models.Component", b =>
                {
                    b.Navigation("PCComponents");
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s33611.Models.PC", b =>
                {
                    b.Navigation("PCComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
